#
# Helm Repositories
# Non standard Helm Chart repositories have to be registered
# Each repository must have 'url', 'type' and 'name' fields
#
---
apiVersion: v1
kind: Secret
metadata:
  name: crossplane-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: crossplane-argocd
  url: https://charts.crossplane.io/stable
  type: helm    